export const COLOR_BACKGROUND = '#F2F2F2';
export const COLOR_PRIMARY = '#00945B';
export const TEXT_COLOR = '#1D211F';
export const FACBOOK_COLOR = '#1977F3';
export const SECONDARY_COLOR = '#EDEEED';
export const TEXTINPUT_COLOR = '#76807C';
export const INITIAL_BUTTON = '#D5D6D5';
export const COLOR_FAVOUR = '#DE8D00';
export const COLOR_SELL = '#C8001A';
export const COLOR_LOOKING_FOR='#005CE7'
export const COLOR_DONATE='#00989B'
